### ISSUE TITLE
Request: Stay in Navigation Move so I can make several jumps

### ISSUE THREAD

**Issue by nemosmithasf** [dexterleng/vimac#235] opened 2020-09-11 16:14 UTC
For example, If I want to change a setting, I have to hit the hint-key several times per jump.

It would be easier if I could could hit the hint-key once, stay in the mode until I'm done with navigation, and then exit.

**Comment by dexterleng** [comment] 2020-09-12 08:34
Closed. Duplicate of #147

**Closed by dexterleng** 2020-09-12 08:34 UTC
